In [12]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder , MinMaxScaler

In [13]:
df=sns.load_dataset('titanic')

In [14]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
df.shape

(891, 15)

In [16]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [18]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
df['deck']

0      NaN
1        C
2      NaN
3        C
4      NaN
      ...
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [21]:
df['age'].fillna(df['age'].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [22]:
df['age'].isnull().sum()

np.int64(177)

In [23]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [24]:
df['deck']

0      NaN
1        C
2      NaN
3        C
4      NaN
      ...
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [25]:
df.drop(columns=['deck'],inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [27]:
df.select_dtypes(include=['object', 'category']).columns

Index(['sex', 'embarked', 'class', 'who', 'embark_town', 'alive'], dtype='object')

In [28]:
df.drop(columns=['alive'], inplace=True)

In [29]:
df['sex'] = df['sex'].map({'male': 0, 'female': 1})

In [30]:
df['embarked'] = df['embarked'].map({'S': 0, 'C': 1, 'Q': 2})

In [31]:
df['class'] = df['class'].cat.codes

In [32]:
df['who'] = df['who'].map({'man': 0, 'woman': 1, 'child': 2})

In [33]:
df.drop(columns=['embark_town'], inplace=True)

In [34]:
df['adult_male'] = df['adult_male'].astype(int)
df['alone'] = df['alone'].astype(int)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    int64
 3   age         714 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    float64
 8   class       891 non-null    int8
 9   who         891 non-null    int64
 10  adult_male  891 non-null    int64
 11  alone       891 non-null    int64
dtypes: float64(3), int64(8), int8(1)
memory usage: 77.6 KB

In [36]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['age_norm', 'fare_norm']] = scaler.fit_transform(df[['age', 'fare']])

print(df[['age', 'age_norm', 'fare', 'fare_norm']].head())

    age  age_norm     fare  fare_norm
0  22.0  0.271174   7.2500   0.014151
1  38.0  0.472229  71.2833   0.139136
2  26.0  0.321438   7.9250   0.015469
3  35.0  0.434531  53.1000   0.103644
4  35.0  0.434531   8.0500   0.015713

In [37]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['age_std', 'fare_std']] = scaler.fit_transform(df[['age', 'fare']])

print(df[['age', 'age_std', 'fare', 'fare_std']].head())

    age   age_std     fare  fare_std
0  22.0 -0.530377   7.2500 -0.502445
1  38.0  0.571831  71.2833  0.786845
2  26.0 -0.254825   7.9250 -0.488854
3  35.0  0.365167  53.1000  0.420730
4  35.0  0.365167   8.0500 -0.486337

In [38]:
print("Mean:", df['age'].mean())
print("Mode:", df['embarked'].mode()[0])
print("Standard Deviation:", df['fare'].std())

Mean: 29.69911764705882
Mode: 0.0
Standard Deviation: 49.6934285971809

In [39]:
import pandas as pd
from sklearn.datasets import load_iris

# Load iris dataset
iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Add species column
df['species'] = iris.target

# Map numeric labels to actual names
df['species'] = df['species'].map({
    0: 'Iris-setosa',
    1: 'Iris-versicolor',
    2: 'Iris-virginica'
})

# Group by species and calculate statistics
grouped = df.groupby('species')

# Display mean
print("Mean:\n", grouped.mean())

# Display standard deviation
print("\nStandard Deviation:\n", grouped.std())

# Display percentiles
print("\nPercentiles (25%, 50%, 75%):\n", grouped.quantile([0.25, 0.5, 0.75]))

Mean:
                  sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
Iris-setosa                  5.006             3.428              1.462
Iris-versicolor              5.936             2.770              4.260
Iris-virginica               6.588             2.974              5.552

                 petal width (cm)
species
Iris-setosa                 0.246
Iris-versicolor             1.326
Iris-virginica              2.026

Standard Deviation:
                  sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
Iris-setosa               0.352490          0.379064           0.173664
Iris-versicolor           0.516171          0.313798           0.469911
Iris-virginica            0.635880          0.322497           0.551895

                 petal width (cm)
species
Iris-setosa              0.105386
Iris-versicolor          0.197753
Iris-virginica           0.274650

Percentiles (25%, 50%, 75%):
                       sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
Iris-setosa     0.25              4.800             3.200              1.400
                0.50              5.000             3.400              1.500
                0.75              5.200             3.675              1.575
Iris-versicolor 0.25              5.600             2.525              4.000
                0.50              5.900             2.800              4.350
                0.75              6.300             3.000              4.600
Iris-virginica  0.25              6.225             2.800              5.100
                0.50              6.500             3.000              5.550
                0.75              6.900             3.175              5.875

                      petal width (cm)
species
Iris-setosa     0.25               0.2
                0.50               0.2
                0.75               0.3
Iris-versicolor 0.25               1.2
                0.50               1.3
                0.75               1.5
Iris-virginica  0.25               1.8
                0.50               2.0
                0.75               2.3